services:
  warehouse-service:
    build: .
    container_name: warehouse-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mariadb://mariadb:3306/Warehouse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_password
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: Warehouse
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb-data:
