version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=InvoiceManager
      - MYSQL_USER=root
      - MYSQL_PASSWORD=xxxx
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mariadb-data:/var/lib/mysql

  myapp:
    build: .
    container_name: myapp
    environment:
      - SPRING_R2DBC_URL=r2dbc:mariadb://mariadb:3306/Warehouse
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=xxxxx
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb-data:
