spring:
  application:
    name: WarehouseService
  r2dbc:
    url: r2dbc:mariadb://mariadb:3306/Warehouse
    #url: r2dbc:mariadb://localhost:3306/Warehouse
    username: root
    password: your_password
